---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: myapp
spec:
  encryptedData:
    root_pass: AgAIKrVuz464JiWqxH2qBa6Js8oBzFdkPb2UOoP+qj5kWGyCVXY840lde5oRDmj6vkwRRt0+VWc77G+1Clq+vF9ZvQTCpybKSMajafdjFs6qV3xpS3mCkLbxCFjBvOqkvr/9G6OWsPvZdmi4s4rgwx2JCn8/7EUUSXfUnCHYNID+nmvhGswJWAaz6G5yRqlVIE618aJLqHJy4MhRv7aq7wPNsjzn/yyotM4vtyDoX3gsIMXibgSWeQceCcLzpTm1KdPhTFqr/eNvj0Q5fWHFXQrHmQcJn6GgDEjjWycoxwXHwJlpiVJI0lZjXhCre7E37slgwp9GfOpsxaJ9dlQU8OdJpnTbbtTchmFxdQ04Nw4YmXG5Fo5ogVBSAglgW+dUvocNvVqsmr1KjKLlzDZnObY9Ma8t8AuDCWVh/g/cTy9OoY+Hi82zfuiecperI/R09PsxJWPhs5CIehmAcKSLBiA2duVQRHahkrCh2yaLcEbP3kiVxcIyppb5TSB6WrGXOoPlETcckq/uS1/64Oo5oFb8QXmW3wZdFTvPozcivWYXNx8w2lHL+xkgrx7IIYUgUbxIdAb9np3ktZxmTVtc8c0/RsqEs3XgUuV2B4T5EKEIXAlOU6TI+HQUQxALusNA+wB+ek6UqiWm7F9jg6JbSJo6Rj3wjPFonEvtdLbILrkao0n6yVK4tlAmUm2i/6hhYAp0+5z6Fkr0KySx+ro=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: myapp
