---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: myapp
spec:
  encryptedData:
    root_pass: AgCRu+sLPObZz/f7DYhxX43rg8CI1T3EnG8shsfIauIf8MP1Eed/R2Q+41+wJvz6fbNgnfwAMiK59+7YaPQKDdiq5FFQ5afUGkSJrTYOpgp0zGXdi9N6/l/hOnMl9bsQnwOVGmBg2aRKF+0LftJNPUxhlPCvvNubZZLStn6VeWNnbu4VRczOs1u2tumEWp15/Is2AkO/NRJlqrQT9Ap2pOt7Jf0JnPAWI7exekL2ZWSiqtxX28IvVb/GKWaNc6ny/9lc3F1RCkGjatcukLVIbeUBZVUS2qktAiOM6ZTWkoXstoA0Rte0+YFM8i2hBHP3+G+VQwYJJX32oVMy/NE561Ogdv+/+QqR6jrg4PNp8DDycdzrLzaJERLl6r4YwnBXJo6xFm/gYZ7VWJZeiIwGVChi01lJr0VL3MH/2V5eH5O11+OC4yVmcwvrifLfUK0CIrUFlnFjSD5hLUCmngJw6lrOtNt/FhvSbCqs4o405JEoAhfMTt0KBLcaMdESr/KcPSIyF1KfXnjpvpKIevl4yEajkBazIo/3YNsOGpnZl8c+xjJXKH1hB+/+I7xs8PecaHi8bf1Motjo+iJTRDcxAiCzXwv8Du0Efp99/gCNvE3cYNiahdBzhB/cZ8CPxbp+3VexVsqeR3wkzDk3vvOr1vGDVmsZQmT8UkJ4dNLtryQAXEfLrG+kwbZ4dCQ+K/4LFUEWAsblW+E/HJZFhyI=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: myapp
